### ISSUE TITLE
theme color in dark?

### ISSUE THREAD

**Issue by manuelsongokuh** [Theverat/NormalmapGenerator#14]
hello

it's possible change theme color in dark? (dark gray, gray, black)..

**Comment by Theverat** [comment]
Good idea.
I added the support for this commit: 6ab63713fd09b24a54d0ac29f28a48e067e32a0b

**Comment by manuelsongokuh** [comment]
thank you!! :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
