### ISSUE TITLE
Compiling for Linux

### ISSUE THREAD

**Issue by SFrav** [Theverat/NormalmapGenerator#18]
Noob question: how do I compile this for debian linux (ubuntu).

**Comment by Theverat** [comment]
This is how I do it:
* Install Qt Creator (I use 4.0.1)
* Import the project (choose "Open Project", then navigate to the Normalmap.pro file and double-click)
* Click compile (or press Ctrl+R)

**Comment by SFrav** [comment]
Thanks!

I get an issue in the ui_mainwindow header. 'Error 2'. This is compiling the current github version of source and Qt creator 3.5.1. I'll try a newer version ...

**Comment by Theverat** [comment]
The ui_mainwindow.h is auto-generated, try to delete it, re-run qmake and try to build again.

**Comment by SFrav** [comment]
No, that didn't do the job. After updating QT creator it gives errors on QUrl in mainwindow.cpp.

**Comment by Theverat** [comment]
What's the exact message?
I'm using Qt. 5.6.0 to compile.

**Comment by SFrav** [comment]
That's it. Installed 5.6.0 and now compiled. Thanks!
