### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by brothermechanic** [Theverat/NormalmapGenerator#19]
https://paste.pound-python.org/show/zwipXvk4zhSsadnqX4kf/

**Comment by Theverat** [comment]
Error seems to be `error: fabs was not declared in this scope`.

Try to add 
`include <cmath>`
to the file ssaogenerator.cpp: https://github.com/Theverat/NormalmapGenerator/blob/master/src_generators/ssaogenerator.cpp#L25

**Comment by brothermechanic** [comment]
Thank you!!!!
This is what i get
https://i.imgur.com/tpXFO8Q.jpg
Great!
