### ISSUE TITLE
Normal map is "shifted"

### ISSUE THREAD

**Issue by mkdotcom** [Theverat/NormalmapGenerator#20]
Hello
Thanks for this great project.
I've noticed something weird: the normal map is kind of 'shifted' (few pixels) compared to the real texture.
When light is moving over it, the texture looks like distorted because of that.

**Comment by Theverat** [comment]
Can you upload an example, e.g. a texture where the effect is particularly strong?
I never noticed this effect, maybe it's caused by the Sobel kernel. You could try to activate the "advanced" checkbox, then switch from Sobel to Prewitt in the dropdown that appears and see how that works.

**Comment by mkdotcom** [comment]
i guess it's not a bug but inherent to generated normal map, as i have the same effect when creating normal map with photoshop or other tools

**Comment by mkdotcom** [comment]
the issue disappears when using the "normal map size" settings to (greatly) reduce the size of the generated normal map 
the loss of quality is usually acceptable (at least for me)
