### ISSUE TITLE
small image + normal map size 10% -> crash

### ISSUE THREAD

**Issue by mkdotcom** [Theverat/NormalmapGenerator#21]
very small white image: 
![4525](https://cloud.githubusercontent.com/assets/10907322/24041210/a7aa351e-0b0c-11e7-89be-f02316de567c.png)

Load the attached image, then set 10% in the "normal map size" and the app will crash
Same thing when doing a queue process with the same 10% parameter
I guess there is a small issue when generated normal map is too small

**Comment by Theverat** [comment]
Thanks for letting me know.
It should be fixed now, can you confirm?

**Comment by mkdotcom** [comment]
looks good !
thanks!
