### ISSUE TITLE
ssaogenerator.cpp:69:36: error: ‘fabs’ was not declared in this scope

### ISSUE THREAD

**Issue by brothermechanic** [Theverat/NormalmapGenerator#25]
Hello
I can't build it
https://paste.pound-python.org/show/TobcoDOMEY8do3uQrMIj/
Please create fix)
Thank you

**Comment by Theverat** [comment]
use the branch 3d_preview (i fixed it there) or fix it yourself by doing what I described here:
https://github.com/Theverat/NormalmapGenerator/issues/19
Also, what is wrong with the encoding of your linked file. Nearly unreadable.

**Comment by brothermechanic** [comment]
Thank you
Sorry, i forget that)))
Super software for linux users!
There is package i created for Gentoo linux
https://github.com/brothermechanic/cg/blob/master/media-gfx/NormalmapGenerator/NormalmapGenerator-9999.ebuild
