### ISSUE TITLE
Platform independent support (e.g., macOS)

### ISSUE THREAD

**Issue by IntellectualKitty** [Theverat/NormalmapGenerator#28]
As a Mac user, platform independent support would be extremely helpful!

There is platform independent windowing and graphics API support available such as [GLFW](https://github.com/glfw/glfw) and [SDL](libsdl.org).

**Comment by Theverat** [comment]
I'm pretty sure that it compiles on macos (at least it worked in the past).
I don't use any platform-dependent functions and I can compile the program on Linux and Windows, however I can't compile for macos.

**Comment by schroef** [comment]
@IntellectualKitty Have you tried compiling it for OSX?

**Comment by IntellectualKitty** [comment]
No, I didn't make the attempt to compile it for OSX.

My normal mapping needs are fairly limited.  I found this online system (http://cpetry.github.io/NormalMap-Online/) that does everything that I need.
